-- LMS Supabase Schema
-- This script creates tables, relationships, and necessary extensions.
-- Run in Supabase SQL Editor (safe to re-run; uses IF NOT EXISTS where applicable).

-- Enable useful extensions (idempotent)
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- USERS / PROFILES

-- Profiles table mirrors auth.users and stores role and display info.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  avatar_url text,
  role text check (role in ('student','instructor','admin')) default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_role on public.profiles(role);

-- COURSES

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  instructor_id uuid not null references public.profiles(id) on delete restrict,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_courses_instructor on public.courses(instructor_id);
create index if not exists idx_courses_published on public.courses(is_published);

-- ENROLLMENTS (student <-> course)

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text check (role in ('student','ta')) default 'student',
  created_at timestamptz not null default now(),
  unique (course_id, user_id)
);

create index if not exists idx_enrollments_course on public.enrollments(course_id);
create index if not exists idx_enrollments_user on public.enrollments(user_id);

-- MODULES (Course content grouping)

create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_modules_course on public.modules(course_id);

-- LESSONS

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.modules(id) on delete cascade,
  title text not null,
  content text,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_lessons_module on public.lessons(module_id);

-- ASSIGNMENTS

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text,
  due_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_assignments_course on public.assignments(course_id);
create index if not exists idx_assignments_due on public.assignments(due_at);

-- SUBMISSIONS

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  submitted_at timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assignment_id, student_id)
);

create index if not exists idx_submissions_assignment on public.submissions(assignment_id);
create index if not exists idx_submissions_student on public.submissions(student_id);

-- GRADES

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.submissions(id) on delete cascade,
  grader_id uuid not null references public.profiles(id) on delete restrict,
  score numeric(5,2) check (score >= 0),
  feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (submission_id)
);

create index if not exists idx_grades_submission on public.grades(submission_id);

-- ANNOUNCEMENTS

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete restrict,
  title text not null,
  message text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_announcements_course on public.announcements(course_id);

-- Timestamps maintenance triggers

-- Generic set updated_at function
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Attach updated_at triggers
drop trigger if exists trg_courses_updated on public.courses;
create trigger trg_courses_updated before update on public.courses
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_modules_updated on public.modules;
create trigger trg_modules_updated before update on public.modules
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_lessons_updated on public.lessons;
create trigger trg_lessons_updated before update on public.lessons
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_assignments_updated on public.assignments;
create trigger trg_assignments_updated before update on public.assignments
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_submissions_updated on public.submissions;
create trigger trg_submissions_updated before update on public.submissions
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_grades_updated on public.grades;
create trigger trg_grades_updated before update on public.grades
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_announcements_updated on public.announcements;
create trigger trg_announcements_updated before update on public.announcements
for each row execute procedure public.set_updated_at();

-- Auto-create profile for new auth.users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'student')
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

-- Attach trigger to auth.users
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
